build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - localPlugin/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Dependency Plugin
dependency-plugin:
  - antibytes-dependency/**/*

# Version Plugin
coverage-plugin:
  - antibytes-coverage/**/*

# Grammar Tools Plugin
grammar-tools-plugin:
  - antibytes-grammar-tools/**/*

# Publishing Plugin
publishing-plugin:
  - antibytes-publishing/**/*

# Configuration Plugin
configuration-plugin:
  - antibytes-configuration/**/*

# Gradle Utils Plugin
gradle-utils-plugin:
  - antibytes-gradle-utils/**/*

# Gradle test utils Plugin
gradle-test-utils-plugin:
  - antibytes-gradle-test-utils/**/*
