build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - localPlugin/dependency/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Dependency Plugin
dependency-plugin:
  - antibytes-dependency/**/*

# Version Plugin
coverage-plugin:
  - antibytes-coverage/**/*

# Publishing Plugin
publishing-plugin:
  - antibytes-publishing/**/*
